const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={approved:'Aprovado',failed:'Falhou',blocked:'Bloqueado · limite técnico',out_of_scope:'Fora do escopo autônomo'};
const scopeLabels={autonomo:'Escopo autônomo',fora_do_escopo:'Fora do escopo autônomo'};
const selected=new Set();let catalog=null,visible=[];
function addOptions(id,values,map={}){[...values].sort().forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(map[v]||v)}</option>`))}
function stat(t,n){return `<article class="stat"><b>${Number(n)||0}</b><span>${esc(t)}</span></article>`}
function renderCatalogStats(){const s=catalog.summary.by_status;$('catalogStats').innerHTML=stat('Total mapeado',catalog.summary.total)+stat('Executados pelo agente',catalog.summary.executed)+stat('Aprovados',s.approved)+stat('Falhas',s.failed)+stat('Bloqueados (pagamento)',s.blocked)+stat('Fora do escopo autônomo',s.out_of_scope)}
function renderCatalog(){const q=$('search').value.trim().toLowerCase(),status=$('status').value,channel=$('channel').value,priority=$('priority').value,scopeF=$('scope').value;visible=catalog.cases.filter(c=>(!status||c.status===status)&&(!channel||c.channel===channel)&&(!priority||c.priority===priority)&&(!scopeF||c.scope===scopeF)&&(!q||[c.id,c.title,c.area,c.channel].join(' ').toLowerCase().includes(q)));$('catalogCount').textContent=`${visible.length} de ${catalog.cases.length} casos`;$('catalogRows').innerHTML=visible.length?visible.map(c=>{const ev=safeEvidence(c.evidence);return `<article class="case ${selected.has(c.id)?'selected':''}" data-id="${esc(c.id)}"><div class="case-head"><input class="pick" type="checkbox" ${selected.has(c.id)?'checked':''} aria-label="Selecionar ${esc(c.id)}"><div><div class="case-id">${esc(c.id)}</div><div class="case-title">${esc(c.title)}</div></div></div><div class="badges"><span class="badge ${esc(c.status)}">${esc(labels[c.status]||c.status)}</span><span class="badge">${esc(c.priority)}</span><span class="badge">${esc(c.channel)}</span><span class="badge">${esc(c.area)}</span><span class="badge">${esc(scopeLabels[c.scope]||c.scope)}</span></div><div class="case-meta">${c.observed?esc(c.observed):esc(c.reason||'')}</div><div class="case-meta">Perfis executados: ${esc((c.execution_profiles||[]).join(' · ')||'não executado')}</div><details><summary>${ev.length?ev.length+' screenshot(s) · ':''}pré-condições e notas</summary>${ev.length?'<h4>Evidências</h4><ul>'+ev.map((p,i)=>`<li><a href="${esc(p)}" target="_blank" rel="noopener noreferrer">Evidência ${i+1}</a></li>`).join('')+'</ul>':''}<h4>Pré-condições</h4><ul>${(c.preconditions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Notas</h4><ul>${(c.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></article>`}).join(''):'<div class="empty">Nenhum caso corresponde aos filtros.</div>';document.querySelectorAll('.pick').forEach(box=>box.onchange=e=>{const card=e.target.closest('.case'),id=card.dataset.id;e.target.checked?selected.add(id):selected.delete(id);card.classList.toggle('selected',e.target.checked);updateSelection()});updateSelection()}
function updateSelection(){$('selection').hidden=!selected.size;$('selectionCount').textContent=`${selected.size} caso${selected.size===1?'':'s'} selecionado${selected.size===1?'':'s'}`}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2400)}
async function copyRequest(){const ids=[...selected].sort();const lines=ids.map(id=>{const c=catalog.cases.find(x=>x.id===id);return `${id} — ${c.title}`});const text=`Solicito preparação/execução dos casos APCAP abaixo, respeitando pré-condições, segurança, encerramento autônomo e evidências sanitizadas:\n\n${lines.join('\n')}\n\nInforme primeiro quais podem rodar imediatamente e quais dependem de infraestrutura ou autorização.`;try{await navigator.clipboard.writeText(text);toast('Solicitação copiada. Envie na conversa com o agente.')}catch{toast('O navegador bloqueou a cópia. Copie os IDs selecionados manualmente.')}}
function safeEvidence(v){return Array.isArray(v)?v.filter(p=>/^evidence\/[A-Z0-9-]+\/[a-z0-9-]+\.png$/.test(p)):[]}
function renderResults(report){const s=report.summary||{};$('resultStats').innerHTML=stat('Casos executados',s.total)+stat('Aprovados',s.passed)+stat('Falhas',s.failed)+stat('Bloqueados',s.blocked)+stat('Perfis cobertos',Object.keys(report.browserCoverage||{}).length)+stat('Screenshots',report.cases.reduce((n,c)=>n+safeEvidence(c.evidence).length,0));$('resultRows').innerHTML=report.cases.length?report.cases.map(c=>{const evidence=safeEvidence(c.evidence);return `<tr><td><b>${esc(c.id)}</b><br>${esc(c.title)}</td><td>${esc(c.execution)}</td><td><span class="badge ${c.status==='passed'?'approved':(c.status==='blocked'?'blocked':'failed')}">${c.status==='passed'?'Aprovado':(c.status==='blocked'?'Bloqueado':'Falhou')}</span></td><td>${esc((c.projects||[]).join(', '))}</td><td><details><summary>${evidence.length} screenshot(s)</summary>${evidence.map((p,i)=>`<a href="${esc(p)}" target="_blank" rel="noopener noreferrer">Evidência ${i+1}</a>`).join('<br>')}</details></td></tr>`}).join(''):'<tr><td colspan="5">Nenhum resultado publicado.</td></tr>'}
Promise.all([fetch('data/review-catalog.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('data/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([cat,report])=>{catalog=cat;$('meta').textContent=`${cat.summary.total} casos mapeados · ${report.summary.total} executados pelo agente: ${report.summary.passed} aprovados, ${report.summary.failed} falha(s) e ${report.summary.blocked} bloqueado(s) · ${cat.summary.by_status.out_of_scope} fora do escopo autônomo · atualização ${report.generatedAt}`;renderCatalogStats();renderResults(report);addOptions('status',new Set(cat.cases.map(c=>c.status)),labels);addOptions('channel',new Set(cat.cases.map(c=>c.channel)));addOptions('priority',new Set(cat.cases.map(c=>c.priority)));addOptions('scope',new Set(cat.cases.map(c=>c.scope)),scopeLabels);['search','status','channel','priority','scope'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderCatalog));$('selectVisible').onclick=()=>{visible.forEach(c=>selected.add(c.id));renderCatalog()};$('clear').onclick=()=>{selected.clear();renderCatalog()};$('copy').onclick=copyRequest;document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));$('catalogView').hidden=btn.dataset.view!=='catalog';$('resultsView').hidden=btn.dataset.view!=='results';$('simulationView').hidden=btn.dataset.view!=='simulation';$('selection').hidden=btn.dataset.view!=='catalog'||!selected.size});renderCatalog()}).catch(e=>{console.error(e);$('meta').textContent='Falha ao carregar os dados sanitizados.';$('catalogRows').innerHTML='<div class="empty">Não foi possível carregar o catálogo.</div>'});

/* ---- Simulação matemática ---- */
function simBlock(b){let h=`<article class="notice"><h3>${esc(b.title)}</h3>`;
if(b.text)h+=`<p>${esc(b.text)}</p>`;
if(b.list)h+=`<ul>${b.list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
if(b.table)h+=`<div class="table-wrap"><table><thead><tr>${b.table.head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${b.table.rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
if(b.images)h+=`<div class="shots">${b.images.map(i=>`<figure><a href="${esc(i.src)}" target="_blank" rel="noopener nofollow"><img src="${esc(i.src)}" alt="${esc(i.caption||'')}" loading="lazy"></a><figcaption>${esc(i.caption||'')}</figcaption></figure>`).join('')}</div>`;
if(b.note)h+=`<p><small>${esc(b.note)}</small></p>`;
return h+'</article>'}
function renderSimulation(sim){$('simStats').innerHTML=(sim.stats||[]).map(s=>`<article class="stat"><b>${esc(s.value)}</b><span>${esc(s.label)}</span></article>`).join('');
$('simBody').innerHTML=`<div class="list-meta"><b>${esc(sim.status||'')}</b><span>Atualização ${esc(sim.generatedAt||'—')}</span></div>`+(sim.sections||[]).map(simBlock).join('')}
fetch('data/simulation.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderSimulation).catch(()=>{$('simBody').innerHTML='<div class="empty">Simulação ainda não publicada.</div>'});
