const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={approved:'Aprovado',implemented_needs_validation:'Implementado · validar',candidate_ready_to_automate:'Candidato à automação',conditional_infrastructure:'Infraestrutura condicional',blocked_external_or_human:'Bloqueado / decisão humana'};
const selected=new Set();let catalog=null,visible=[];
function addOptions(id,values,map={}){[...values].sort().forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(map[v]||v)}</option>`))}
function stat(t,n){return `<article class="stat"><b>${Number(n)||0}</b><span>${esc(t)}</span></article>`}
function renderCatalogStats(){const s=catalog.summary.by_status;$('catalogStats').innerHTML=stat('Total',catalog.summary.total)+stat('Aprovados',s.approved)+stat('Implementados',s.implemented_needs_validation)+stat('Prontos para automatizar',s.candidate_ready_to_automate)+stat('Condicionais / bloqueados',s.conditional_infrastructure+s.blocked_external_or_human)}
function renderCatalog(){const q=$('search').value.trim().toLowerCase(),status=$('status').value,channel=$('channel').value,priority=$('priority').value;visible=catalog.cases.filter(c=>(!status||c.status===status)&&(!channel||c.channel===channel)&&(!priority||c.priority===priority)&&(!q||[c.id,c.title,c.area,c.channel].join(' ').toLowerCase().includes(q)));$('catalogCount').textContent=`${visible.length} de ${catalog.cases.length} casos`;$('catalogRows').innerHTML=visible.length?visible.map(c=>`<article class="case ${selected.has(c.id)?'selected':''}" data-id="${esc(c.id)}"><div class="case-head"><input class="pick" type="checkbox" ${selected.has(c.id)?'checked':''} aria-label="Selecionar ${esc(c.id)}"><div><div class="case-id">${esc(c.id)}</div><div class="case-title">${esc(c.title)}</div></div></div><div class="badges"><span class="badge ${esc(c.status)}">${esc(labels[c.status]||c.status)}</span><span class="badge">${esc(c.priority)}</span><span class="badge">${esc(c.channel)}</span><span class="badge">${esc(c.area)}</span>${c.sensitive_state_change?'<span class="badge blocked_external_or_human">Estado sensível</span>':''}</div><div class="case-meta">Perfis: ${esc((c.execution_profiles||[]).join(' · ')||'a definir')}</div><details><summary>Pré-condições e notas</summary><h4>Pré-condições</h4><ul>${(c.preconditions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Notas</h4><ul>${(c.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></article>`).join(''):'<div class="empty">Nenhum caso corresponde aos filtros.</div>';document.querySelectorAll('.pick').forEach(box=>box.onchange=e=>{const card=e.target.closest('.case'),id=card.dataset.id;e.target.checked?selected.add(id):selected.delete(id);card.classList.toggle('selected',e.target.checked);updateSelection()});updateSelection()}
function updateSelection(){$('selection').hidden=!selected.size;$('selectionCount').textContent=`${selected.size} caso${selected.size===1?'':'s'} selecionado${selected.size===1?'':'s'}`}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2400)}
async function copyRequest(){const ids=[...selected].sort();const lines=ids.map(id=>{const c=catalog.cases.find(x=>x.id===id);return `${id} — ${c.title}`});const text=`Solicito preparação/execução dos casos APCAP abaixo, respeitando pré-condições, segurança, encerramento autônomo e evidências sanitizadas:\n\n${lines.join('\n')}\n\nInforme primeiro quais podem rodar imediatamente e quais dependem de infraestrutura ou autorização.`;try{await navigator.clipboard.writeText(text);toast('Solicitação copiada. Envie na conversa com o agente.')}catch{toast('O navegador bloqueou a cópia. Copie os IDs selecionados manualmente.')}}
function safeEvidence(v){return Array.isArray(v)?v.filter(p=>/^evidence\/[A-Z0-9-]+\/[a-z0-9-]+\.png$/.test(p)):[]}
function renderResults(report){const s=report.summary||{};$('resultStats').innerHTML=stat('Casos executados',s.total)+stat('Aprovados',s.passed)+stat('Falhas',s.failed)+stat('Perfis cobertos',Object.keys(report.browserCoverage||{}).length)+stat('Screenshots',report.cases.reduce((n,c)=>n+safeEvidence(c.evidence).length,0));$('resultRows').innerHTML=report.cases.length?report.cases.map(c=>{const evidence=safeEvidence(c.evidence);return `<tr><td><b>${esc(c.id)}</b><br>${esc(c.title)}</td><td>${esc(c.execution)}</td><td><span class="badge ${c.status==='passed'?'approved':'blocked_external_or_human'}">${c.status==='passed'?'Aprovado':'Falhou'}</span></td><td>${esc((c.projects||[]).join(', '))}</td><td><details><summary>${evidence.length} screenshot(s)</summary>${evidence.map((p,i)=>`<a href="${esc(p)}" target="_blank" rel="noopener noreferrer">Evidência ${i+1}</a>`).join('<br>')}</details></td></tr>`}).join(''):'<tr><td colspan="5">Nenhum resultado publicado.</td></tr>'}
Promise.all([fetch('data/review-catalog.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('data/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([cat,report])=>{catalog=cat;$('meta').textContent=`${cat.summary.total} casos mapeados · ${report.summary.total} executados e aprovados · atualização ${cat.generatedAt}`;renderCatalogStats();renderResults(report);addOptions('status',new Set(cat.cases.map(c=>c.status)),labels);addOptions('channel',new Set(cat.cases.map(c=>c.channel)));addOptions('priority',new Set(cat.cases.map(c=>c.priority)));['search','status','channel','priority'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderCatalog));$('selectVisible').onclick=()=>{visible.forEach(c=>selected.add(c.id));renderCatalog()};$('clear').onclick=()=>{selected.clear();renderCatalog()};$('copy').onclick=copyRequest;document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));$('catalogView').hidden=btn.dataset.view!=='catalog';$('resultsView').hidden=btn.dataset.view!=='results';$('selection').hidden=btn.dataset.view!=='catalog'||!selected.size});renderCatalog()}).catch(e=>{console.error(e);$('meta').textContent='Falha ao carregar os dados sanitizados.';$('catalogRows').innerHTML='<div class="empty">Não foi possível carregar o catálogo.</div>'});
