const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={approved:'Aprovado',failed:'Falhou',blocked:'Bloqueado · limite técnico',out_of_scope:'Fora do escopo autônomo'};
const scopeLabels={autonomo:'Escopo autônomo',fora_do_escopo:'Fora do escopo autônomo'};
const selected=new Set();let catalog=null,visible=[];
function addOptions(id,values,map={}){[...values].sort().forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(map[v]||v)}</option>`))}
function stat(t,n){return `<article class="stat"><b>${Number(n)||0}</b><span>${esc(t)}</span></article>`}
function renderCatalogStats(){const s=catalog.summary.by_status;$('catalogStats').innerHTML=stat('Total mapeado',catalog.summary.total)+stat('Executados pelo agente',catalog.summary.executed)+stat('Aprovados',s.approved)+stat('Falhas',s.failed)+stat('Bloqueados (pagamento)',s.blocked)+stat('Fora do escopo autônomo',s.out_of_scope)}
function renderCatalog(){const q=$('search').value.trim().toLowerCase(),status=$('status').value,channel=$('channel').value,priority=$('priority').value,scopeF=$('scope').value;visible=catalog.cases.filter(c=>(!status||c.status===status)&&(!channel||c.channel===channel)&&(!priority||c.priority===priority)&&(!scopeF||c.scope===scopeF)&&(!q||[c.id,c.title,c.area,c.channel].join(' ').toLowerCase().includes(q)));$('catalogCount').textContent=`${visible.length} de ${catalog.cases.length} casos`;$('catalogRows').innerHTML=visible.length?visible.map(c=>{const ev=safeEvidence(c.evidence);return `<article class="case ${selected.has(c.id)?'selected':''}" data-id="${esc(c.id)}"><div class="case-head"><input class="pick" type="checkbox" ${selected.has(c.id)?'checked':''} aria-label="Selecionar ${esc(c.id)}"><div><div class="case-id">${esc(c.id)}</div><div class="case-title">${esc(c.title)}</div></div></div><div class="badges"><span class="badge ${esc(c.status)}">${esc(labels[c.status]||c.status)}</span><span class="badge">${esc(c.priority)}</span><span class="badge">${esc(c.channel)}</span><span class="badge">${esc(c.area)}</span><span class="badge">${esc(scopeLabels[c.scope]||c.scope)}</span></div><div class="case-meta">${c.observed?esc(c.observed):esc(c.reason||'')}</div><div class="case-meta">Perfis executados: ${esc((c.execution_profiles||[]).join(' · ')||'não executado')}</div><details><summary>${ev.length?ev.length+' screenshot(s) · ':''}pré-condições e notas</summary>${ev.length?'<h4>Evidências</h4><ul>'+ev.map((p,i)=>`<li><a href="${esc(p)}" target="_blank" rel="noopener noreferrer">Evidência ${i+1}</a></li>`).join('')+'</ul>':''}<h4>Pré-condições</h4><ul>${(c.preconditions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Notas</h4><ul>${(c.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></article>`}).join(''):'<div class="empty">Nenhum caso corresponde aos filtros.</div>';document.querySelectorAll('.pick').forEach(box=>box.onchange=e=>{const card=e.target.closest('.case'),id=card.dataset.id;e.target.checked?selected.add(id):selected.delete(id);card.classList.toggle('selected',e.target.checked);updateSelection()});updateSelection()}
function updateSelection(){$('selection').hidden=!selected.size;$('selectionCount').textContent=`${selected.size} caso${selected.size===1?'':'s'} selecionado${selected.size===1?'':'s'}`}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2400)}
async function copyRequest(){const ids=[...selected].sort();const lines=ids.map(id=>{const c=catalog.cases.find(x=>x.id===id);return `${id} — ${c.title}`});const text=`Solicito preparação/execução dos casos APCAP abaixo, respeitando pré-condições, segurança, encerramento autônomo e evidências sanitizadas:\n\n${lines.join('\n')}\n\nInforme primeiro quais podem rodar imediatamente e quais dependem de infraestrutura ou autorização.`;try{await navigator.clipboard.writeText(text);toast('Solicitação copiada. Envie na conversa com o agente.')}catch{toast('O navegador bloqueou a cópia. Copie os IDs selecionados manualmente.')}}
function safeEvidence(v){return Array.isArray(v)?v.filter(p=>/^evidence\/[A-Z0-9-]+\/[a-z0-9-]+\.png$/.test(p)):[]}
/* ---- Resultados por rodada (registro por data) ---- */
let allRuns=[],runDateAtual=null;
function normalizeRuns(report){report=report||{};if(Array.isArray(report.runs)&&report.runs.length)return{runs:report.runs,runDateAtual:report.runDateAtual||report.runs[0].runDate};
const fallbackDate=(report.generatedAt||'').slice(0,10)||'—';return{runs:[Object.assign({runDate:fallbackDate,rotulo:'Execução',status:'concluido'},report)],runDateAtual:fallbackDate}}
function findRun(runDate){return allRuns.find(r=>r.runDate===runDate)||allRuns[0]||{}}
function renderRunSelector(){const sel=$('runSelect');if(!sel)return;const ordered=[...allRuns].sort((a,b)=>(b.runDate||'').localeCompare(a.runDate||''));sel.innerHTML=ordered.map(r=>`<option value="${esc(r.runDate)}">${esc(r.runDate)} · ${esc(r.rotulo||'')}</option>`).join('');sel.value=runDateAtual;sel.onchange=()=>renderResults(findRun(sel.value))}
function renderResults(run){run=run||{};const s=run.summary||{};const cases=Array.isArray(run.cases)?run.cases:[];const blocked=run.status==='aguardando-ambiente'||run.status==='bloqueado';const noData=!cases.length;
const metaEl=$('runMeta');if(metaEl)metaEl.textContent=`${esc(run.rotulo||'')} · status: ${esc(run.status||'—')}`;
const blockEl=$('runBlock');if(blockEl){if(run.bloqueio){blockEl.hidden=false;blockEl.innerHTML=`<strong>Rodada aguardando ambiente</strong><p>${esc(run.bloqueio)}</p>`}else{blockEl.hidden=true;blockEl.innerHTML=''}}
const tableWrap=$('resultTableWrap');if(tableWrap)tableWrap.hidden=blocked&&noData;
$('resultStats').innerHTML=stat('Casos executados',s.total)+stat('Aprovados',s.passed)+stat('Falhas',s.failed)+stat('Bloqueados',s.blocked)+stat('Perfis cobertos',Object.keys(run.browserCoverage||{}).length)+stat('Screenshots',cases.reduce((n,c)=>n+safeEvidence(c.evidence).length,0));
$('resultRows').innerHTML=cases.length?cases.map(c=>{const evidence=safeEvidence(c.evidence);return `<tr><td><b>${esc(c.id)}</b><br>${esc(c.title)}</td><td>${esc(c.execution)}</td><td><span class="badge ${c.status==='passed'?'approved':(c.status==='blocked'?'blocked':'failed')}">${c.status==='passed'?'Aprovado':(c.status==='blocked'?'Bloqueado':'Falhou')}</span></td><td>${esc((c.projects||[]).join(', '))}${c.lote?`<br><small>${esc(c.lote)}${c.priority?' · '+esc(c.priority):''}</small>`:''}</td><td><details><summary>${evidence.length} screenshot(s)</summary>${evidence.map((p,i)=>`<a href="${esc(p)}" target="_blank" rel="noopener noreferrer">Evidência ${i+1}</a>`).join('<br>')}</details></td></tr>`}).join(''):'<tr><td colspan="5">Nenhum resultado publicado.</td></tr>'}
Promise.all([fetch('data/review-catalog.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('data/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([cat,report])=>{catalog=cat;const norm=normalizeRuns(report);allRuns=norm.runs;runDateAtual=norm.runDateAtual;const cur=findRun(runDateAtual);const s=cur.summary||{};$('meta').textContent=`${(cat.summary&&cat.summary.total)||'—'} casos mapeados · rodada ${esc(cur.runDate||'—')} (${esc(cur.rotulo||'')}): ${s.total||0} executados, ${s.passed||0} aprovados, ${s.failed||0} falha(s) e ${s.blocked||0} bloqueado(s) · ${(cat.summary&&cat.summary.by_status&&cat.summary.by_status.out_of_scope)||'—'} fora do escopo autônomo · atualização ${esc(report.generatedAt||'—')}`;renderCatalogStats();renderScopeNotice(cat,cur);renderRunSelector();renderResults(cur);addOptions('status',new Set(cat.cases.map(c=>c.status)),labels);addOptions('channel',new Set(cat.cases.map(c=>c.channel)));addOptions('priority',new Set(cat.cases.map(c=>c.priority)));addOptions('scope',new Set(cat.cases.map(c=>c.scope)),scopeLabels);['search','status','channel','priority','scope'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderCatalog));$('selectVisible').onclick=()=>{visible.forEach(c=>selected.add(c.id));renderCatalog()};$('clear').onclick=()=>{selected.clear();renderCatalog()};$('copy').onclick=copyRequest;document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));$('catalogView').hidden=btn.dataset.view!=='catalog';$('resultsView').hidden=btn.dataset.view!=='results';$('simulationView').hidden=btn.dataset.view!=='simulation';$('provaView').hidden=btn.dataset.view!=='prova';$('caminhoView').hidden=btn.dataset.view!=='caminho';$('selection').hidden=btn.dataset.view!=='catalog'||!selected.size});renderCatalog()}).catch(e=>{console.error(e);$('meta').textContent='Falha ao carregar os dados sanitizados.';$('catalogRows').innerHTML='<div class="empty">Não foi possível carregar o catálogo.</div>'});

/* ---- Simulação matemática ---- */
function simBlock(b){let h=`<article class="notice"><h3>${esc(b.title)}</h3>`;
if(b.text)h+=`<p>${esc(b.text)}</p>`;
if(b.list)h+=`<ul>${b.list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
if(b.table)h+=`<div class="table-wrap"><table><thead><tr>${b.table.head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${b.table.rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
if(b.images)h+=`<div class="shots">${b.images.map(i=>`<figure><a href="${esc(i.src)}" target="_blank" rel="noopener nofollow"><img src="${esc(i.src)}" alt="${esc(i.caption||'')}" loading="lazy"></a><figcaption>${esc(i.caption||'')}</figcaption></figure>`).join('')}</div>`;
if(b.note)h+=`<p><small>${esc(b.note)}</small></p>`;
return h+'</article>'}
function renderSimulation(sim){$('simStats').innerHTML=(sim.stats||[]).map(s=>`<article class="stat"><b>${esc(s.value)}</b><span>${esc(s.label)}</span></article>`).join('');
$('simBody').innerHTML=`<div class="list-meta"><b>${esc(sim.status||'')}</b><span>Atualização ${esc(sim.generatedAt||'—')}</span></div>`+(sim.sections||[]).map(simBlock).join('')}
fetch('data/simulation.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderSimulation).catch(()=>{$('simBody').innerHTML='<div class="empty">Simulação ainda não publicada.</div>'});

function renderScopeNotice(cat,cur){const el=$('scopeNotice');if(!el)return;const s=cat.summary,b=s.by_status,v=s.verdicts||(b.approved+b.failed),cs=cur.summary||{};el.innerHTML=`<strong>Por que ${v} de ${s.total}?</strong> O catálogo mapeia <b>${s.total}</b> casos, mas só recebem veredito os que o agente executa <b>do início ao fim sozinho</b> contra o HML real, sem humano, sem mock e sem backend fora de alcance: <b>${v} com veredito</b> (${b.approved} aprovados e ${b.failed} falhas). Os outros <b>${b.out_of_scope}</b> dependem de decisão de negócio, hardware físico, dado de produção ou verificação de backend sem acesso — cada um traz o motivo no card. A rodada corrente <b>${esc(cur.runDate||'')}</b> soma <b>${cs.executed||0}</b> casos (${cs.passed||0} aprovados, ${cs.failed||0} falhas). Screenshots são cruas, sem mascaramento. As abas <b>Simular Estouro da Sorte</b> e <b>Prova do Motor</b> trazem a medição estatística da rodada, congelada no instante da pausa, e <b>Simular Caminho da Sorte</b> declara por que ainda não há medição daquele jogo. Todas leem os mesmos números da mesma fonte.`}

/* ---- Prova do Motor ---- */
const veredictoLabels={aprovado:'Aprovado',falhou:'Falhou',parcial:'Parcial','amostra insuficiente':'Amostra insuficiente',pendente:'Pendente','sem veredito':'Sem veredito'};
function veredictoClass(v){if(v==='aprovado')return 'approved';if(v==='falhou')return 'failed';return 'pending'}
function provaCard(p){const v=p.veredito||'pendente';return `<article class="prova-card"><div class="prova-head"><b>${esc(p.id)}</b><span class="badge ${veredictoClass(v)}">${esc(veredictoLabels[v]||v)}</span></div><h3>${esc(p.titulo)}</h3><p class="prova-pergunta">${esc(p.pergunta)}</p><dl><dt>Fórmula</dt><dd>${esc(p.formula)}</dd><dt>Fonte</dt><dd>${esc(p.fonte)}</dd><dt>Esperado</dt><dd>${esc(p.esperado)}</dd><dt>Tolerância</dt><dd>${esc(p.tolerancia)}</dd><dt>Critério de veredito</dt><dd>${esc(p.criterioVeredito)}</dd>${p.medido!=null?`<dt>Medido</dt><dd>${esc(p.medido)}</dd>`:''}</dl>${(p.observacoes||[]).length?`<ul class="prova-obs">${(p.observacoes||[]).map(o=>`<li>${esc(o)}</li>`).join('')}</ul>`:''}</article>`}
function provaResumo(d){const r=d.resumo,o=d.rodada;if(!r&&!o)return '';const money=c=>'R$ '+(c/100).toLocaleString('pt-BR',{minimumFractionDigits:2});const partes=[];if(o){partes.push(`Rodada ${o.runDate||'—'} · ${o.status||''}`);if(o.arrecadadoCentavos!=null&&o.alvoCentavos)partes.push(`${money(o.arrecadadoCentavos)} de ${money(o.alvoCentavos)} aplicados`);if(o.sessoes!=null)partes.push(`${o.sessoes} contas · ${(o.rodadasJogadas||0).toLocaleString('pt-BR')} jogadas`)}if(r)partes.push(`${r.aprovados||0} aprovada(s), ${r.falhou||0} falha(s), ${(r.semVeredito||0)+(r.amostraInsuficiente||0)+(r.pendentes||0)} sem veredito · prova ${r.estado||''}`);return `<div class="prova-resumo">${partes.map(esc).join(' — ')}</div>`}
function renderProva(data){data=data||{};$('provaIntro').innerHTML=esc(data.introducao||'')+(data.congelado&&data.notaCongelamento?`<br><br><b>Medição congelada.</b> ${esc(data.notaCongelamento)}`:'');$('provaCards').innerHTML=provaResumo(data)+(data.provas||[]).map(provaCard).join('')||'<div class="empty">Nenhuma prova publicada.</div>';$('provaRegras').innerHTML=(data.regras||[]).length?`<h3>Regras da prova</h3><ol>${data.regras.map(r=>`<li>${esc(r)}</li>`).join('')}</ol>`:''}
fetch('data/prova.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderProva).catch(()=>{$('provaCards').innerHTML='<div class="empty">Prova do Motor ainda não publicada.</div>'});

function renderCaminho(d){d=d||{};const badge=d.status==='bloqueado'?'<span class="badge failed">bloqueado</span>':'<span class="badge">'+esc(d.status||'')+'</span>';
$('csEstado').innerHTML=badge+' '+esc(d.estado||'');
const bloco=(t,l)=>l&&l.length?`<h3>${esc(t)}</h3><ul>${l.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';
$('csBody').innerHTML=bloco('Por que esta bloqueado',d.porQueBloqueado)+bloco('O que ja esta provado',d.oQueJaEstaProvado)+bloco('Condicoes para destravar',d.condicoesParaDestravar)+(d.generatedAt?`<p class="case-meta">Atualizado em ${esc(d.generatedAt)}</p>`:'');}
fetch('data/caminho-sorte.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(renderCaminho).catch(()=>{$('csEstado').textContent='Simulação do Caminho da Sorte ainda não publicada.'});
